openapi: 3.1.0
info:
  title: Git Integration Service (GTP Action)
  version: 1.0.1
  description: >
    API for Git operations used by Augmented Team GPT — includes committing text, uploading documents, checking
    repository status, and pushing to remote.
servers:
  - url: https://ubiquitous-fiesta-4xrwxq44wh57q6-8001.app.github.dev
    description: Git Integration Service (Codespace HTTPS endpoint)
paths:
  /:
    get:
      operationId: healthCheck
      summary: Health Check
      description: Check if the Git Integration Service is running
      responses:
        "200":
          description: Service is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  repo:
                    type: string
  /status:
    get:
      operationId: getRepositoryStatus
      summary: Get Repository Status
      description: Returns current repository status and pending changes
      responses:
        "200":
          description: Repository status
          content:
            application/json:
              schema:
                type: object
                properties:
                  repo_path:
                    type: string
                  branch:
                    type: string
                  has_changes:
                    type: boolean
                  changes:
                    type: array
                    items:
                      type: string
                  error:
                    type: string
  /commit/text:
    post:
      operationId: commitTextContent
      summary: Commit text content to a file
      description: Write text content to a file and commit it to the repository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - file_path
              properties:
                content:
                  type: string
                  description: The text content to write
                file_path:
                  type: string
                  description: Path to save the file (relative to repo root)
                commit_message:
                  type: string
                  description: Optional commit message
      responses:
        "200":
          description: Text committed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  commit_hash:
                    type: string
                  file_path:
                    type: string

  /deleteFile:
    post:
      operationId: deleteFile
      summary: Delete a file
      description: Delete a file from the repository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
                  description: Path to the file to delete
                commit_message:
                  type: string
                  description: Optional commit message
              required:
                - file_path
      responses:
        "200":
          description: File deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  file_path:
                    type: string
        "404":
          description: File not found
        "500":
          description: Error deleting file

  /extract/{file_path}:
    get:
      operationId: extractFileContent
      summary: Extract text content from any file
      description: Extract text content from any file in the repository (including binary files like .pptx, .pdf, .docx)
      parameters:
        - name: file_path
          in: path
          required: true
          schema:
            type: string
          description: Path to the file to extract content from
      responses:
        "200":
          description: File content extracted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  file_path:
                    type: string
                  file_type:
                    type: string
                    enum: ["text", "binary"]
                  content:
                    type: string
                    description: Text content (for text files)
                  extracted_content:
                    type: string
                    description: Extracted text content (for binary files)
                  size:
                    type: integer
                    description: File size in bytes
                  extension:
                    type: string
                    description: File extension (for binary files)
                  error:
                    type: string
                    description: Error message if extraction failed
        "404":
          description: File not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
  /commit/document:
    post:
      operationId: commitDocument
      summary: Commit uploaded document
      description: Upload and commit a document to the repository
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - file_path
              properties:
                file:
                  type: string
                  format: binary
                file_path:
                  type: string
                commit_message:
                  type: string
      responses:
        "200":
          description: Document committed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  commit_hash:
                    type: string
                  file_path:
                    type: string

  /deleteFile:
    post:
      operationId: deleteFile
      summary: Delete a file
      description: Delete a file from the repository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
                  description: Path to the file to delete
                commit_message:
                  type: string
                  description: Optional commit message
              required:
                - file_path
      responses:
        "200":
          description: File deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  file_path:
                    type: string
        "404":
          description: File not found
        "500":
          description: Error deleting file

  /extract/{file_path}:
    get:
      operationId: extractFileContent
      summary: Extract text content from any file
      description: Extract text content from any file in the repository (including binary files like .pptx, .pdf, .docx)
      parameters:
        - name: file_path
          in: path
          required: true
          schema:
            type: string
          description: Path to the file to extract content from
      responses:
        "200":
          description: File content extracted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  file_path:
                    type: string
                  file_type:
                    type: string
                    enum: ["text", "binary"]
                  content:
                    type: string
                    description: Text content (for text files)
                  extracted_content:
                    type: string
                    description: Extracted text content (for binary files)
                  size:
                    type: integer
                    description: File size in bytes
                  extension:
                    type: string
                    description: File extension (for binary files)
                  error:
                    type: string
                    description: Error message if extraction failed
        "404":
          description: File not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
  /push:
    post:
      operationId: pushChanges
      summary: Push committed changes
      description: Push changes to the remote repository
      responses:
        "200":
          description: Changes pushed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  output:
                    type: string
  /commit-and-push:
    post:
      operationId: commitAndPush
      summary: Commit and push content
      description: Commit text to a file and push to remote in one operation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - file_path
              properties:
                content:
                  type: string
                file_path:
                  type: string
                commit_message:
                  type: string
      responses:
        "200":
          description: Commit and push successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  commit_hash:
                    type: string
                  file_path:
                    type: string

  /deleteFile:
    post:
      operationId: deleteFile
      summary: Delete a file
      description: Delete a file from the repository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
                  description: Path to the file to delete
                commit_message:
                  type: string
                  description: Optional commit message
              required:
                - file_path
      responses:
        "200":
          description: File deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  file_path:
                    type: string
        "404":
          description: File not found
        "500":
          description: Error deleting file

  /extract/{file_path}:
    get:
      operationId: extractFileContent
      summary: Extract text content from any file
      description: Extract text content from any file in the repository (including binary files like .pptx, .pdf, .docx)
      parameters:
        - name: file_path
          in: path
          required: true
          schema:
            type: string
          description: Path to the file to extract content from
      responses:
        "200":
          description: File content extracted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  file_path:
                    type: string
                  file_type:
                    type: string
                    enum: ["text", "binary"]
                  content:
                    type: string
                    description: Text content (for text files)
                  extracted_content:
                    type: string
                    description: Extracted text content (for binary files)
                  size:
                    type: integer
                    description: File size in bytes
                  extension:
                    type: string
                    description: File extension (for binary files)
                  error:
                    type: string
                    description: Error message if extraction failed
        "404":
          description: File not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
