name: Common Deploy Orchestrator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Git Integration Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-git-integration
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Trigger Vector Search Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-vector-search
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Trigger Update GPT Instructions Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-update-gpt-instructions
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Deployment Summary
        run: |
          echo "🚀 Common deployment orchestration completed!"
          echo "📦 Features deployed:"
          echo "  - Git Integration"
          echo "  - Vector Search" 
          echo "  - Update GPT Instructions"
          echo "🔗 Check individual feature workflows for detailed status"

