name: Common CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          # Install common dependencies for all features
          pip install pytest flake8 black isort
          
          # Install feature-specific dependencies
          if [ -f "src/features/vector-search/requirements.txt" ]; then
            pip install -r src/features/vector-search/requirements.txt
          fi
          if [ -f "src/integration/git/build-requirements.txt" ]; then
            pip install -r src/integration/git/build-requirements.txt
          fi

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Format check with black
        run: black --check .

      - name: Import sorting check with isort
        run: isort --check-only .

      - name: Run tests
        run: |
          # Run tests for each feature that has them
          if [ -f "src/features/vector-search/test_setup.py" ]; then
            python -m pytest src/features/vector-search/test_setup.py -v
          fi
          if [ -f "src/integration/git/test-service.py" ]; then
            python -m pytest src/integration/git/test-service.py -v
          fi

      - name: Architecture compliance check
        run: |
          echo "🏗️ Checking architecture compliance..."
          
          # Check that features follow the 5-7 file rule
          for feature_dir in src/features/*/; do
            if [ -d "$feature_dir" ]; then
              feature_name=$(basename "$feature_dir")
              file_count=$(find "$feature_dir" -type f -name "*.py" -o -name "*.md" -o -name "*.yml" -o -name "*.yaml" -o -name "*.txt" -o -name "*.json" | wc -l)
              echo "📁 $feature_name: $file_count files"
              
              # Check for required files
              if [ ! -f "$feature_dir/README.md" ]; then
                echo "⚠️  Missing README.md in $feature_name"
              fi
            fi
          done
          
          echo "✅ Architecture compliance check completed"

