apiVersion: apps/v1
kind: ContainerApp
metadata:
  name: [feature-name]
  namespace: augmented-teams
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: [feature-name]
        feature: [feature-name]
    spec:
      containers:
      - name: [feature-name]
        image: augmentedteamacr.azurecr.io/[feature-name]:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
  service:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

